name: CI/CD Test Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: gcc

          - os: windows-latest
            toolchain: mingw

          - os: windows-latest
            toolchain: visual-studio

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Set up MinGW
        if: matrix.toolchain == 'mingw'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Configure MSVC Developer Command Prompt
        if: matrix.toolchain == 'visual-studio'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build CMake project
        run: |
          python make.py --toolchain ${{ matrix.toolchain }} setup
          python make.py --toolchain ${{ matrix.toolchain }} build

      - name: Run Golden Tests
        run: |
          python make.py --toolchain ${{ matrix.toolchain }} test
