name: CI/CD Test Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Build CMake project
        run: |
          python make.py setup
          python make.py build

      - name: Run Golden Tests
        run: |
          python make.py test
