name: Test examples on debug-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure CMake
        run: |
          cmake -S . -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build cmake-build-debug --config Debug

      - name: Run tests
        run: |
          bash tests/run_tests.sh
